package com.kt.restful.model;

public enum ApiDefine {
	GET_APN_BY_PDP_ID("GET_APN_BY_PDP_ID", 1),
	GET_APN_BY_PDN_ID("GET_APN_BY_PDN_ID", 1),
	GET_ROAM_REST_BY_ID("GET_ROAM_REST_BY_ID", 1),
	GET_LTE_ROAM_REST_BY_ID("GET_LTE_ROAM_REST_BY_ID", 1),
	ADD_HLR_TEMP("ADD_HLR_TEMP", 5),
	GET_HLR_TEMP("GET_HLR_TEMP", 1),
	DEL_HLR_TEMP("DEL_HLR_TEMP", 1),
	ADD_SUBS("ADD_SUBS", 9),
	MOD_HSS_STATIC_IP("MOD_HSS_STATIC_IP", 3),
	UPT_SUBS("UPT_SUBS", 3),
	DEL_SUBS("DEL_SUBS", 2),
	GET_SUBS_DETAIL("GET_SUBS_DETAIL", 2),
	GET_SUBS_MDN_BY_IMSI("GET_SUBS_MDN_BY_IMSI", 1),
	GET_SUBS_IMSI_BY_MDN("GET_SUBS_IMSI_BY_MDN", 1),
	GET_HSS_STATIC_IP("GET_HSS_STATIC_IP", 1),
	REM_HSS_STATIC_IP("REM_HSS_STATIC_IP", 4),
	GET_APN_FOR_SUBS("GET_APN_FOR_SUBS", 1),
	GET_HSS_APN_FOR_SUBS("GET_HSS_APN_FOR_SUBS", 1),
	GET_ROAM_REST_FOR_SUBS("GET_ROAM_REST_FOR_SUBS", 1),
	GET_LTE_ROAM_REST_FOR_SUBS("GET_LTE_ROAM_REST_FOR_SUBS", 1),
	SET_NETWORK_BAR("SET_NETWORK_BAR", 2),
	SET_NETWORK_UNBAR("SET_NETWORK_UNBAR", 2),
	SET_LTE_NETWORK_BAR("SET_LTE_NETWORK_BAR", 2),
	SET_LTE_NETWORK_UNBAR("SET_LTE_NETWORK_UNBAR", 2),
	SND_CANCEL_LOC("SND_CANCEL_LOC", 2),
	SND_LTE_CANCEL_LOC("SND_LTE_CANCEL_LOC", 2),
	GET_SGSN_LOC_FOR_SUBS("GET_SGSN_LOC_FOR_SUBS", 1),
	GET_MSC_LOC_FOR_SUBS("GET_MSC_LOC_FOR_SUBS", 1),
	GET_MME_LOC_FOR_SUBS("GET_MME_LOC_FOR_SUBS", 1),
	UPT_SUBS_ATT("UPT_SUBS_ATT", 2),
	MOD_STATIC_IP("MOD_STATIC_IP", 3),
	GET_STATIC_IP("GET_STATIC_IP", 1),
	REM_STATIC_IP("REM_STATIC_IP", 3),
	
	
	/* BSS-IOT */
	/*Subscription Management API */
	OPEN_SUBS("OPEN_SUBS", 0),
	TERMINATE_SUBS("TERM_SUBS", 0),
	CHG_SUBS_STS("CHG_SUBS_STS", 0),
	CHG_SUBS_DEV("CHG_SUBS_DEV", 0),
	CHG_SERV_NUMBER("CHG_SVC_NUMBER", 0),
	OTA_REQ("OTA_REQ", 0),
	RETREIVE_SUBS_STS("RTRV_SUBS_STS", 0),
	
	/*SIM Management API */
	DOWNLOAD_PROF_REQ("DOWN_PROF_REQ", 0),
	ENABLE_ES2_PROF_REQ("ES2_ENB_PROF_REQ", 0),
	DISABLE_ES2_PROF_REQ("ES2_DSB_PROF_REQ", 0),
	DELETE_ES2_PROF_REQ("ES2_DEL_PROF_REQ", 0),
	UPT_ES2_SUBS_ADDRESS("ES2_UPT_SUBS_ADDR", 0),
	GET_ES2_EIS("ES2_GET_EIS", 0),
	ENABLE_ES4_PROF_REQ("ES4_ENB_PROF_REQ", 0),
	DISABLE_ES4_PROF_REQ("ES4_DSB_PROF_REQ", 0),
	DELETE_ES4_PROF_REQ("ES4_DEL_PROF_REQ", 0),
	UPT_ES4_SUBS_ADDRESS("ES4_UPT_SUBS_ADDR", 0),
	GET_ES4_EIS("ES4_GET_EIS", 0),
	
	/*Inquiry API */
	INQUIRY("INQUIRY", 0),
	HEALTH_CHECK("HEALTH_CHECK", 0),
		
	/* Callback , Health Check API */
	DOWNLOAD_PROF_CALLBACK("DOWN_PROF_CLBK", 0 ),
	PROF_STS_CHANGE_NOTI("PROF_STS_CHG_NOTI", 0);


	final private String name;
	final private int paramCount;

	private ApiDefine(String name, int paramCount) {
		this.name = name;
		this.paramCount = paramCount;
	}

	public String getName() {
		return name;
	}
	
	public int getParamCount() {
		return paramCount;
	}
}
