package com.kt.restful.model;

public enum ApiDefine {
	GET_APN_BY_PDP_ID("GET_APN_BY_PDP_ID"),
	GET_APN_BY_PDN_ID("GET_APN_BY_PDN_ID"),
	GET_ROAM_REST_BY_ID("GET_ROAM_REST_BY_ID"),
	GET_LTE_ROAM_REST_BY_ID("GET_LTE_ROAM_REST_BY_ID"),
	ADD_HLR_TEMP("ADD_HLR_TEMP"),
	ADD_SUBS("ADD_SUBS"),
	MOD_HSS_STATIC_IP("MOD_HSS_STATIC_IP"),
	UPT_SUBS("UPT_SUBS"),
	DEL_SUBS("DEL_SUBS"),
	GET_SUBS_DETAIL("GET_SUBS_DETAIL"),
	GET_SUBS_MDN_BY_IMSI("GET_SUBS_MDN_BY_IMSI"),
	GET_SUBS_IMSI_BY_MDN("GET_SUBS_IMSI_BY_MDN"),
	GET_HSS_STATIC_IP("GET_HSS_STATIC_IP"),
	REM_HSS_STATIC_IP("REM_HSS_STATIC_IP"),
	GET_PDP_FOR_SUBS("GET_PDP_FOR_SUBS"),
	GET_PDN_FOR_SUBS("GET_PDN_FOR_SUBS"),
	GET_ROAM_REST_FOR_SUBS("GET_ROAM_REST_FOR_SUBS"),
	GET_LTE_ROAM_REST_FOR_SUBS("GET_LTE_ROAM_REST_FOR_SUBS"),
	SET_NETWORK_BAR("SET_NETWORK_BAR"),
	SET_NETWORK_UNBAR("SET_NETWORK_UNBAR"),
	SET_LTE_NETWORK_BAR("SET_LTE_NETWORK_BAR"),
	SET_LTE_NETWORK_UNBAR("SET_LTE_NETWORK_UNBAR"),
	SND_CANCEL_LOC("SND_CANCEL_LOC"),
	SND_LTE_CANCEL_LOC("SND_LTE_CANCEL_LOC"),
	GET_SGSN_LOC_FOR_SUBS("GET_SGSN_LOC_FOR_SUBS"),
	GET_MSC_LOC_FOR_SUBS("GET_MSC_LOC_FOR_SUBS"),
	GET_MME_LOC_FOR_SUBS("GET_MME_LOC_FOR_SUBS"),
	UPT_SUBS_ATT("UPT_SUBS_ATT"),
	MOD_STATIC_IP("MOD_STATIC_IP"),
	GET_STATIC_IP("GET_STATIC_IP"),
	REM_STATIC_IP("REM_STATIC_IP"),
	GET_HLR_TEMP("GET_HLR_TEMP"),
	DEL_HLR_TEMP("DEL_HLR_TEMP");

	final private String name;

	private ApiDefine(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}
}
