package com.kt.restful.model;

public enum ApiDefine {
	
	
	/* IUDR */
	GET_APN_BY_PDP_ID("GET_APN_BY_PDP_ID"),
	GET_APN_BY_PDN_ID("GET_APN_BY_PDN_ID"),
	GET_ROAM_REST_BY_ID("GET_ROAM_REST_BY_ID"),
	GET_LTE_ROAM_REST_BY_ID("GET_LTE_ROAM_REST_BY_ID"),
	ADD_HLR_TEMP("ADD_HLR_TEMP"),
	ADD_SUBS("ADD_SUBS"),
	MOD_HSS_STATIC_IP("MOD_HSS_STATIC_IP"),
	UPT_SUBS("UPT_SUBS"),
	DEL_SUBS("DEL_SUBS"),
	GET_SUBS_DETAIL("GET_SUBS_DETAIL"),
	GET_SUBS_MDN_BY_IMSI("GET_SUBS_MDN_BY_IMSI"),
	GET_SUBS_IMSI_BY_MDN("GET_SUBS_IMSI_BY_MDN"),
	GET_HSS_STATIC_IP("GET_HSS_STATIC_IP"),
	REM_HSS_STATIC_IP("REM_HSS_STATIC_IP"),
	GET_APN_FOR_SUBS("GET_APN_FOR_SUBS"),
	GET_HSS_APN_FOR_SUBS("GET_HSS_APN_FOR_SUBS"),
	GET_ROAM_REST_FOR_SUBS("GET_ROAM_REST_FOR_SUBS"),
	GET_LTE_ROAM_REST_FOR_SUBS("GET_LTE_ROAM_REST_FOR_SUBS"),
	SET_NETWORK_BAR("SET_NETWORK_BAR"),
	SET_NETWORK_UNBAR("SET_NETWORK_UNBAR"),
	SET_LTE_NETWORK_BAR("SET_LTE_NETWORK_BAR"),
	SET_LTE_NETWORK_UNBAR("SET_LTE_NETWORK_UNBAR"),
	SND_CANCEL_LOC("SND_CANCEL_LOC"),
	SND_LTE_CANCEL_LOC("SND_LTE_CANCEL_LOC"),
	GET_SGSN_LOC_FOR_SUBS("GET_SGSN_LOC_FOR_SUBS"),
	GET_MSC_LOC_FOR_SUBS("GET_MSC_LOC_FOR_SUBS"),
	GET_MME_LOC_FOR_SUBS("GET_MME_LOC_FOR_SUBS"),
	UPT_SUBS_ATT("UPT_SUBS_ATT"),
	MOD_STATIC_IP("MOD_STATIC_IP"),
	GET_STATIC_IP("GET_STATIC_IP"),
	REM_STATIC_IP("REM_STATIC_IP"),
	GET_HLR_TEMP("GET_HLR_TEMP"),
	DEL_HLR_TEMP("DEL_HLR_TEMP"),
	
	/* BSS-IOT */
	/*Subscription Management API */
	OPEN_SUBS("OPEN_SUBS"),
	TERMINATE_SUBS("TERM_SUBS"),
	CHG_SUBS_STS("CHG_SUBS_STS"),
	CHG_SUBS_DEV("CHG_SUBS_DEV"),
	CHG_SERV_NUMBER("CHG_SVC_NUMBER"),
	OTA_REQ("OTA_REQ"),
	RETREIVE_SUBS_STS("RTRV_SUBS_STS"),
	
	/*SIM Management API */
	DOWNLOAD_PROF_REQ("DOWN_PROF_REQ"),
	ENABLE_ES2_PROF_REQ("ES2_ENB_PROF_REQ"),
	DISABLE_ES2_PROF_REQ("ES2_DSB_PROF_REQ"),
	DELETE_ES2_PROF_REQ("ES2_DEL_PROF_REQ"),
	UPT_ES2_SUBS_ADDRESS("ES2_UPT_SUBS_ADDR"),
	GET_ES2_EIS("ES2_GET_EIS"),
	ENABLE_ES4_PROF_REQ("ES4_ENB_PROF_REQ"),
	DISABLE_ES4_PROF_REQ("ES4_DSB_PROF_REQ"),
	DELETE_ES4_PROF_REQ("ES4_DEL_PROF_REQ"),
	UPT_ES4_SUBS_ADDRESS("ES4_UPT_SUBS_ADDR"),
	GET_ES4_EIS("ES4_GET_EIS"),
	
	/*Inquiry API */
	INQUIRY("INQUIRY"),
	HEALTH_CHECK("HEALTH_CHECK"),
		
	/* Callback , Health Check API */
	DOWNLOAD_PROF_CALLBACK("DOWN_PROF_CLBK"),
	PROF_STS_CHANGE_NOTI("PROF_STS_CHG_NOTI");
	final private String name;

	private ApiDefine(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}
}
